title: Design Patterns
description: >- # this means to ignore newlines until "baseurl:"
  A repo containing my implementations of Creational, Structural, and Behavioral Design Patterns
github_username:  Battlesquid

include:
  - dist

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache